insert into roles (nombre) values ("ROLE_USER");
insert into roles (nombre) values ("ROLE_ADMIN");
insert into usuarios (nombre, correo, password, puntuacionTotal, fichas, fechaRegistro, enabled, imagenPerfil) values ("Dani", "pruebadani98@gmail.com", "$2a$10$qwe.rdhx61TNOIEEIbPUoOBSWbwunggHgjHV4xBVcKEWXpA1yddP6", 50, 20, current_date(), true, null);
insert into usuarios (nombre, correo, password, puntuacionTotal, fichas, fechaRegistro, enabled, imagenPerfil) values ("Alex", "correo2@gmail.com", "$2a$10$j1QpeH0Qr8DXLPGsW9CD.ep4dW.gYiWVDTpbqf2qOJo37X4u2bYke", 10, 60, current_date(), true, null);
insert into usuarios (nombre, correo, password, puntuacionTotal, fichas, fechaRegistro, enabled, imagenPerfil) values ("Marta", "correo3@gmail.com", "$2a$10$j1QpeH0Qr8DXLPGsW9CD.ep4dW.gYiWVDTpbqf2qOJo37X4u2bYke", 30, 60, current_date(), true, null);
insert into usuarios (nombre, correo, password, puntuacionTotal, fichas, fechaRegistro, enabled, imagenPerfil) values ("Armando", "correo4@gmail.com", "$2a$10$j1QpeH0Qr8DXLPGsW9CD.ep4dW.gYiWVDTpbqf2qOJo37X4u2bYke", 20, 70, current_date(), true, null);
insert into usuarios (nombre, correo, password, puntuacionTotal, fichas, fechaRegistro, enabled, imagenPerfil) values ("Acebal", "correo5@gmail.com", "$2a$10$j1QpeH0Qr8DXLPGsW9CD.ep4dW.gYiWVDTpbqf2qOJo37X4u2bYke", 15, 90, current_date(), true, null);
insert into usuarios (nombre, correo, password, puntuacionTotal, fichas, fechaRegistro, enabled, imagenPerfil) values ("Carolina", "correo6@gmail.com", "$2a$10$j1QpeH0Qr8DXLPGsW9CD.ep4dW.gYiWVDTpbqf2qOJo37X4u2bYke", 15, 90, current_date(), true, null);
insert into linUsuRol (rol_idRol, usuario_idUsuario) values (1,1);
insert into linUsuRol (rol_idRol, usuario_idUsuario) values (2,1);
insert into linUsuRol (rol_idRol, usuario_idUsuario) values (1,2);
insert into linUsuRol (rol_idRol, usuario_idUsuario) values (1,3);
insert into linUsuRol (rol_idRol, usuario_idUsuario) values (1,4);
insert into linUsuRol (rol_idRol, usuario_idUsuario) values (1,5);
insert into linUsuRol (rol_idRol, usuario_idUsuario) values (1,6);
insert into linUsuRol (rol_idRol, usuario_idUsuario) values (2,6);
insert into linUsuUsu (usuario1_idUsuario, usuario2_idUsuario, activo) values (1,2,true);
insert into mensajes (usuUsu_usuario1_idUsuario, usuUsu_usuario2_idUsuario, sender, contenido, tipo) values (1, 2, "Dani", "hola", 0);
insert into mensajes (usuUsu_usuario1_idUsuario, usuUsu_usuario2_idUsuario, sender, contenido, tipo) values (1, 2, "Alex", "hey", 0);
insert into premios (nombre, descripcion, precio, imagen, activo) values ("Camiseta", "Hecha de tela", 5, null, true);
insert into premios (nombre, descripcion, precio, imagen, activo) values ("Gorra", "Perfecta para el verano", 10, null, true);
insert into premios (nombre, descripcion, precio, imagen, activo) values ("Ordenador", "PC de última generación", 5000, null, true);
insert into premios (nombre, descripcion, precio, imagen, activo) values ("Sudadera", "100% algodón", 100, null, true);
insert into premios (nombre, descripcion, precio, imagen, activo) values ("Teclado", "Teclado mecánico", 30, null, true);
insert into premios (nombre, descripcion, precio, imagen, activo) values ("Ratón", "Hasta 10000 DPI", 15, null, true);
insert into linUsuPre (idUsuario, idPremio, fecha) values (1, 1, current_date());
insert into partidas (fecha) values ("2019-4-12");
insert into partidas (fecha) values ("2019-4-10");
insert into partidas (fecha) values (current_date());
insert into partidas (fecha) values (current_date());
insert into partidas (fecha) values (current_date());
insert into partidas (fecha) values (current_date());
insert into partidas (fecha) values (current_date());
insert into partidas (fecha) values (current_date());
insert into linUsuPar (usuario_idUsuario, partida_idPartida, posicionLinea, posicionBingo) values (1, 1, 1, 1);
insert into linUsuPar (usuario_idUsuario, partida_idPartida, posicionLinea, posicionBingo) values (3, 1, 3, 3);
insert into linUsuPar (usuario_idUsuario, partida_idPartida, posicionLinea, posicionBingo) values (4, 1, 4, 4);
insert into linUsuPar (usuario_idUsuario, partida_idPartida, posicionLinea, posicionBingo) values (1, 2, 1, 1);
insert into linUsuPar (usuario_idUsuario, partida_idPartida, posicionLinea, posicionBingo) values (1, 3, 1, 1);
insert into linUsuPar (usuario_idUsuario, partida_idPartida, posicionLinea, posicionBingo) values (2, 1, 2, 2);
insert into linUsuPar (usuario_idUsuario, partida_idPartida, posicionLinea, posicionBingo) values (2, 4, 1, 1);
insert into linUsuPar (usuario_idUsuario, partida_idPartida, posicionLinea, posicionBingo) values (3, 6, 1, 1);