insert into roles (nombre) values ("ROLE_USER");
insert into roles (nombre) values ("ROLE_ADMIN");
insert into usuarios (nombre, correo, password, puntuacionTotal, fichas, fechaRegistro, enabled, imagenPerfil) values ("Dani", "correo@gmail.com", "$2a$10$qwe.rdhx61TNOIEEIbPUoOBSWbwunggHgjHV4xBVcKEWXpA1yddP6", 50, 20, current_date(), true, null);
insert into usuarios (nombre, correo, password, puntuacionTotal, fichas, fechaRegistro, enabled, imagenPerfil) values ("Alex", "correo2@gmail.com", "$2a$10$j1QpeH0Qr8DXLPGsW9CD.ep4dW.gYiWVDTpbqf2qOJo37X4u2bYke", 10, 60, current_date(), true, null);
insert into usuarios (nombre, correo, password, puntuacionTotal, fichas, fechaRegistro, enabled, imagenPerfil) values ("Marta", "correo3@gmail.com", "$2a$10$j1QpeH0Qr8DXLPGsW9CD.ep4dW.gYiWVDTpbqf2qOJo37X4u2bYke", 40, 80, current_date(), true, null);
insert into usuarios (nombre, correo, password, puntuacionTotal, fichas, fechaRegistro, enabled, imagenPerfil) values ("Armando", "correo4@gmail.com", "$2a$10$j1QpeH0Qr8DXLPGsW9CD.ep4dW.gYiWVDTpbqf2qOJo37X4u2bYke", 40, 80, current_date(), true, null);
insert into usuarios (nombre, correo, password, puntuacionTotal, fichas, fechaRegistro, enabled, imagenPerfil) values ("Acebal", "correo5@gmail.com", "$2a$10$j1QpeH0Qr8DXLPGsW9CD.ep4dW.gYiWVDTpbqf2qOJo37X4u2bYke", 40, 80, current_date(), true, null);
insert into linUsuRol (rol_idRol, usuario_idUsuario) values (1,1);
insert into linUsuRol (rol_idRol, usuario_idUsuario) values (2,1);
insert into linUsuRol (rol_idRol, usuario_idUsuario) values (1,2)
insert into linUsuUsu (usuario1_idUsuario, usuario2_idUsuario, activo) values (1,2,true);
insert into mensajes (usuUsu_usuario1_idUsuario, usuUsu_usuario2_idUsuario, sender, contenido, tipo) values (1, 2, "Dani", "hola", 0);
insert into mensajes (usuUsu_usuario1_idUsuario, usuUsu_usuario2_idUsuario, sender, contenido, tipo) values (1, 2, "Alex", "hey", 0);
insert into salas (nombre, idPropietario, jugando, publica) values ("Sala1", 1, false, true);
insert into salas (nombre, idPropietario, jugando, publica, password) values ("Sala2", 1, false, false, "$2a$10$qwe.rdhx61TNOIEEIbPUoOBSWbwunggHgjHV4xBVcKEWXpA1yddP6");
insert into salas (nombre, idPropietario, jugando, publica) values ("Sala3", 1, true, true);
insert into salas (nombre, idPropietario, jugando, publica) values ("Sala4", 1, false, true);
insert into salas (nombre, idPropietario, jugando, publica) values ("Sala5", 1, false, true);
insert into salas (nombre, idPropietario, jugando, publica) values ("Sala6", 1, false, true);
insert into salas (nombre, idPropietario, jugando, publica) values ("Sala7", 1, false, true);
insert into salas (nombre, idPropietario, jugando, publica) values ("Sala8", 1, false, true);
insert into salas (nombre, idPropietario, jugando, publica) values ("Sala9", 1, false, true);
insert into salas (nombre, idPropietario, jugando, publica) values ("Sala10", 1, false, true);
insert into salas (nombre, idPropietario, jugando, publica) values ("Sala11", 1, false, true);
insert into salas (nombre, idPropietario, jugando, publica) values ("Sala12", 1, false, true);
insert into salas (nombre, idPropietario, jugando, publica) values ("Sala13", 1, false, true);
insert into salas (nombre, idPropietario, jugando, publica) values ("Sala14", 1, false, true);
insert into salas (nombre, idPropietario, jugando, publica) values ("Sala15", 1, false, true);
insert into salas (nombre, idPropietario, jugando, publica) values ("Sala16", 1, false, true);
insert into salas (nombre, idPropietario, jugando, publica) values ("Sala17", 1, false, true);
insert into salas (nombre, idPropietario, jugando, publica) values ("Sala18", 1, false, true);
insert into premios (nombre, descripcion, precio, imagen) values ("Camiseta", "Hecha de tela", 5, null);
insert into linUsuPre (idUsuario, idPremio, fecha) values (1, 1, current_date());
insert into partidas (fecha) values ("2019-4-12");
insert into partidas (fecha) values ("2019-4-10");
insert into partidas (fecha) values (current_date());
insert into partidas (fecha) values (current_date());
insert into partidas (fecha) values (current_date());
insert into partidas (fecha) values (current_date());
insert into partidas (fecha) values (current_date());
insert into partidas (fecha) values (current_date());
insert into linUsuPar (usuario_idUsuario, partida_idPartida, posicionLinea, posicionBingo) values (1, 1, 1, 1);
insert into linUsuPar (usuario_idUsuario, partida_idPartida, posicionLinea, posicionBingo) values (3, 1, 3, 3);
insert into linUsuPar (usuario_idUsuario, partida_idPartida, posicionLinea, posicionBingo) values (4, 1, 4, 4);
insert into linUsuPar (usuario_idUsuario, partida_idPartida, posicionLinea, posicionBingo) values (1, 2, 1, 1);
insert into linUsuPar (usuario_idUsuario, partida_idPartida, posicionLinea, posicionBingo) values (1, 3, 1, 1);
insert into linUsuPar (usuario_idUsuario, partida_idPartida, posicionLinea, posicionBingo) values (2, 1, 2, 2);
insert into linUsuPar (usuario_idUsuario, partida_idPartida, posicionLinea, posicionBingo) values (2, 4, 1, 1);
insert into linUsuPar (usuario_idUsuario, partida_idPartida, posicionLinea, posicionBingo) values (3, 6, 1, 1);